### DISCUSSION TITLE
Saving / exporting rules to file

### DISCUSSION THREAD

**Discussion by OlafKocanda** [lablabs/prometheus-alert-overrider#1] [Q&A] [answered]
Hi there,

first of all thank you for you prometheus alert overrider. It is exactly what I was looking for.

I got the overrider to work (starting with go build and run). However, it only prints the output to the terminal, instead of saving it to a file. Am I missing something here?

What I tried:

1.  `go build -o prometheus_alert_overrider main.go`
2. ` ./prometheus_alert_overrider_test ./examples  `

The result is the following. As the parts are overridden I guess it worked correctly. However I would prefer it to be saved in a new yaml file to be used for prometheus rules
Is this implemented or am I just missing something?

```
groups:
- name: k8s-node
  rules:
  - alert: K8SNodeCPUUtilization
    expr: K8SNodeCPUUtilization{kubernetes_cluster!="kube-dev"} > 90
    for: 5m
    labels:
      group: system
      severity: high
    annotations:
      identifier: '{{ $labels.kubernetes_cluster }}/{{ $labels.instance_name }}'
      msg: Node CPU ultilization by containers has been over 90% for more than 5m.
      reason: Node CPU ultilization by containers is high. Recalculate CPU request
        and limits.
      value: '{{ printf "%.2f" $value }}%'
  - alert: K8SNodeMemoryUtilization
    expr: K8SNodeMemoryUtilization{kubernetes_cluster!="kube-dev"} > 90
    for: 5m
    labels:
      group: system
      severity: high
    annotations:
      identifier: '{{ $labels.kubernetes_cluster }}/{{ $labels.instance_name }}'
      msg: Node memory ultilization by containers has been over 90% for more than
        5m.
      reason: Node memory ultilization by containers is high. Recalculate Memory request
        and limits.
      value: '{{ printf "%.2f" $value }}%'
- name: k8s-workload-container-overrides
  rules: []
- name: k8s-node
  rules:
  - alert: K8SNodeCPUUtilization
    expr: K8SNodeCPUUtilization{kubernetes_cluster!="kube-dev"} > 90
    for: 5m
    labels:
      group: system
      severity: high
    annotations:
      identifier: '{{ $labels.kubernetes_cluster }}/{{ $labels.instance_name }}'
      msg: Node CPU ultilization by containers has been over 90% for more than 5m.
      reason: Node CPU ultilization by containers is high. Recalculate CPU request
        and limits.
      value: '{{ printf "%.2f" $value }}%'
- name: k8s-workload-container-overrides
  rules:
  - alert: K8SNodeCPUUtilizationDev
    expr: |
      K8SNodeCPUUtilization{kubernetes_cluster="kube-dev",kubernetes_cluster!="kube-dev"} > 90
    for: 1h
    labels:
      group: system
      severity: warning
    annotations:
      identifier: '{{ $labels.kubernetes_cluster }}/{{ $labels.instance_name }}'
      msg: Node CPU ultilization by containers has been over 90% for more than 1h.
      reason: Node CPU ultilization by containers is high. Recalculate CPU request
        and limits.
      value: '{{ printf "%.2f" $value }}%'
```

Thanks for your help!
