### ISSUE TITLE
Wrong negation for regex

### ISSUE THREAD

**Issue by varac** [lablabs/prometheus-alert-overrider#11]
I want to override an alert using a regex to match the label, but the resulting alert includes a wrong `!=~` instead of a `!~`. 
This example shows it:

```
❯ cat bug-regex.rules 
---
groups:
- name: regex_negation
  rules:

  - alert: test
    expr: up

  - alert: test_override
    override: ["test"]
    expr: up{label=~"a|b"}

❯ prometheus-alert-overrider bug-regex.rules
groups:
- name: regex_negation
  rules:
  - alert: test
    expr: up{label!=~"a|b"}
  - alert: test_override
    expr: up{label=~"a|b"}
```

**Comment by varac** [comment]
I can confirm #13 fixes the above example bug::

```
❯ prometheus_alert_overrider bug-regex.rules                         
groups:
- name: regex_negation
  rules:
  - alert: test
    expr: up{label!~"a|b"}
  - alert: test_override
    expr: up{label=~"a|b"}

```

@robgordon89   Thanks !
