### ISSUE TITLE
Can't override query with multiple metrics combined with OR

### ISSUE THREAD

**Issue by varac** [lablabs/prometheus-alert-overrider#15]
The below example shows that [prometheus-alert-overrider](https://github.com/lablabs/prometheus-alert-overrider) can't properly override a query with multiple metrics combined with OR.
The first metric is overridden fine, but the second one is not:

```
❯ cat bug-multiple-metrics-in-query.rules 
groups:
- name: example
  rules:

  - alert: test
    expr: 'probe_http_status_code <= 199 or probe_http_status_code >= 400'

  - alert: test_override
    override: ["test"]
    expr: 'probe_http_status_code{instance="https://example.org"} <= 199 or probe_http_status_code{instance="https://example.org"} >= 400'


❯ prometheus_alert_overrider bug-multiple-metrics-in-query.rules
groups:
- name: example
  rules:
  - alert: test
    expr: probe_http_status_code{instance!="https://example.org" <= 199 or probe_http_status_codeinstance="https://example.org"}
      <= 199 or probe_http_status_code >= 400
  - alert: test_override
    expr: probe_http_status_code{instance="https://example.org"} <= 199 or probe_http_status_code{instance="https://example.org"}
      >= 400

```
